### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by PowerSchill** [sous-chefs/kismet#19]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Update all CHANGELOGs to follow standard defined at <https://keepachangelog.com/>

Issue sprouted from sous-chefs/meta/issues/101. If not applicable then issue should be closed.

**Comment by jsugiarto** [comment]
Hello @PowerSchill, I came here from the hacktoberfest filter. 
Am I right that the changes needed are mainly:
- adding the "Added" / "Changed" / "Deprecated" / ... headings
- adding dates to the release version numbers?

Thanks!

**Comment by PowerSchill** [comment]
Yes, that is correct. Also make sure to add the "unreleased" section.
